version: "3"


services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      ssh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
    links:
      - db:db
    networks:
      - "backend"


  db:
    image: postgres:10-alpine
    expose:
      - "5432"
    networks:
      - "backend"
    environment:
      - POSTGRESS_DB=app
      - POSTGRESS_USER=postgres
      - POSTGRESS_PASSWORD=supersecretpassword
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
    backend:
      driver: bridge
